### ISSUE TITLE
可否增加上传文件后删除的功能

### ISSUE THREAD

**Issue by LeeJunhui** [simple-uploader/vue-uploader#7]
现在的版本处理是上传的过程中，可以暂停和取消上传任务。但是上传完成后，如果用户需要删掉这个文件，就无法实现了

**Comment by dolymood** [comment]
这个是支持的，只是默认UI样式是成功后隐藏了 x 按钮，如果你需要可以删除的话，可以利用样式覆盖，强制改为 block 即可：

```css
  .uploader-file[status="success"] .uploader-file-remove {
    display: block;
  }
```
